name = "nock-names-website"
compatibility_date = "2025-07-26"
routes = [
  { pattern = "nocknames.com", custom_domain = true }
]

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"

